const PatrocinadoresSlide = () => {
    return (
        <>
            <div className="patrocinadores-slide">
                <ul className="patrocinadores-logo-slide">
                    <li>
                        <img
                            src="/patrocinadores/negativos/zendal.png"
                            alt="Zendal"
                        />
                    </li>
                    <li>
                        <img
                            src="/patrocinadores/negativos/atendo.png"
                            alt="Atendo"
                        />
                    </li>
                    <li>
                        <img
                            src="/patrocinadores/negativos/fpns.png"
                            alt="Fundación Profesor Novoa Santos"
                        />
                    </li>
                    <li>
                        <img
                            src="/patrocinadores/negativos/ribera.png"
                            alt="Ribera Salud"
                        />
                    </li>
                    <li>
                        <img
                            src="/patrocinadores/negativos/fbgs.png"
                            alt="Fundación Biomédica Galicia Sur"
                        />
                    </li>
                    <li>
                        <img
                            src="/patrocinadores/negativos/iisgs.png"
                            alt="Instituto de Investigación Sanitaria Galicia Sur"
                        />
                    </li>
                    <li>
                        <img
                            src="/patrocinadores/negativos/domusvi.png"
                            alt="DomusVi"
                        />
                    </li>
                    <li>
                        <img
                            src="/patrocinadores/negativos/gradiant.png"
                            alt="Gradiant"
                        />
                    </li>
                    <li>
                        <img
                            src="/patrocinadores/negativos/plexus.png"
                            alt="Plexus"
                        />
                    </li>
                    <li>
                        <img
                            src="/patrocinadores/negativos/balidea.png"
                            alt="Balidea"
                        />
                    </li>
                    <li>
                        <img
                            src="/patrocinadores/negativos/galaria.png"
                            alt="Galaria"
                        />
                    </li>
                    <li>
                        <img
                            src="/patrocinadores/negativos/insati.png"
                            alt="Insati Innovation"
                        />
                    </li>
                    <li>
                        <img
                            src="/patrocinadores/negativos/qida.png"
                            alt="Qida"
                        />
                    </li>
                    <li>
                        <img
                            src="/patrocinadores/negativos/pm4gov.png"
                            alt="PM4GOV"
                        />
                    </li>
                    <li>
                        <img
                            src="/patrocinadores/negativos/atlanttic.png"
                            alt="atlanTTic"
                        />
                    </li>
                    <li>
                        <img
                            src="/patrocinadores/negativos/longevita.png"
                            alt="Longevita"
                        />
                    </li>
                    <li>
                        <img
                            src="/patrocinadores/negativos/afaga.png"
                            alt="AFAGA Alzhéimer"
                        />
                    </li>
                </ul>
                <ul className="patrocinadores-logo-slide" aria-hidden="true">
                    <li>
                        <img
                            src="/patrocinadores/negativos/zendal.png"
                            alt="Zendal"
                        />
                    </li>
                    <li>
                        <img
                            src="/patrocinadores/negativos/atendo.png"
                            alt="Atendo"
                        />
                    </li>
                    <li>
                        <img
                            src="/patrocinadores/negativos/fpns.png"
                            alt="Fundación Profesor Novoa Santos"
                        />
                    </li>
                    <li>
                        <img
                            src="/patrocinadores/negativos/ribera.png"
                            alt="Ribera Salud"
                        />
                    </li>
                    <li>
                        <img
                            src="/patrocinadores/negativos/fbgs.png"
                            alt="Fundación Biomédica Galicia Sur"
                        />
                    </li>
                    <li>
                        <img
                            src="/patrocinadores/negativos/iisgs.png"
                            alt="Instituto de Investigación Sanitaria Galicia Sur"
                        />
                    </li>
                    <li>
                        <img
                            src="/patrocinadores/negativos/domusvi.png"
                            alt="DomusVi"
                        />
                    </li>
                    <li>
                        <img
                            src="/patrocinadores/negativos/gradiant.png"
                            alt="Gradiant"
                        />
                    </li>
                    <li>
                        <img
                            src="/patrocinadores/negativos/plexus.png"
                            alt="Plexus"
                        />
                    </li>
                    <li>
                        <img
                            src="/patrocinadores/negativos/balidea.png"
                            alt="Balidea"
                        />
                    </li>
                    <li>
                        <img
                            src="/patrocinadores/negativos/galaria.png"
                            alt="Galaria"
                        />
                    </li>
                    <li>
                        <img
                            src="/patrocinadores/negativos/insati.png"
                            alt="Insati Innovation"
                        />
                    </li>
                    <li>
                        <img
                            src="/patrocinadores/negativos/qida.png"
                            alt="Qida"
                        />
                    </li>
                    <li>
                        <img
                            src="/patrocinadores/negativos/pm4gov.png"
                            alt="PM4GOV"
                        />
                    </li>
                    <li>
                        <img
                            src="/patrocinadores/negativos/atlanttic.png"
                            alt="atlanTTic"
                        />
                    </li>
                    <li>
                        <img
                            src="/patrocinadores/negativos/longevita.png"
                            alt="Longevita"
                        />
                    </li>
                    <li>
                        <img
                            src="/patrocinadores/negativos/asp-sl.png"
                            alt="Alexa Smart Properties Senior Living"
                        />
                    </li>
                    <li>
                        <img
                            src="/patrocinadores/negativos/afaga.png"
                            alt="AFAGA Alzhéimer"
                        />
                    </li>
                </ul>
            </div>
        </>
    )
}

export default PatrocinadoresSlide
